### ISSUE TITLE
Validate codeInsee and commune name in zonage attribute

### ISSUE THREAD

**Issue by guillett** [betagouv/annuaire-api#10]

**Comment by jdesboeufs** [comment]
Possible de décrire un petit peu cette issue ?
Merci :)

**Comment by guillett** [comment]
Les fichiers d'établissement créés manuellement ou via xxx comme https://github.com/betagouv/annuaire-api/blob/master/data/60/ccas_Clermont.yaml par exemple.

Les communes de référence sont listées par code Insee qui ne sont pas dont la validité n'est pas testée. À ces codes Insee sont associés le nom de la commune (sans que ce nom soit utilisé dans la logique mais c'est utile pour les humains que nous sommes).

Par exemple :

```
zonage:
  communes:
    - 60157 Clermont
```


Je pensais que les codes pouvaient être testés voire que les noms le soient aussi.

**Comment by jdesboeufs** [comment]
Oui c'est testable, mais est-ce pertinent d'avoir le nom, qui lui va pouvoir évoluer au fil du temps ?

**Comment by jdesboeufs** [comment]
Ajouté dans la PR #133
