### ISSUE TITLE
Corriger les problèmes d'encodage

### ISSUE THREAD

**Issue by guillett** [betagouv/annuaire-api#115]
https://etablissements-publics.api.gouv.fr/v3/communes/71017/mds

**Comment by jdesboeufs** [comment]
Tu as un peu de contexte sur ce problème ? C'est isolé ?

**Comment by guillett** [comment]
Certains établissements sont récupérés auprès de fichiers à plat ou d'API de portails d'OpenData. Je pense que c'est pour ceux là que des problèmes d'encodage apparaissent.

**Comment by jdesboeufs** [comment]
En effet c'est le CSV de la Saône-et-Loire qui est en UTF16-LE. Je corrige ça de suite.
