### ISSUE TITLE
Ajout des SDSEI et de leurs antennes

### ISSUE THREAD

**Issue by guillett** [betagouv/annuaire-api#37]
Les points d'accueil inconditionnel devraient être dans cet annuaire.
Nous pouvons commencer par [ceux des Pyrénées Atlantiques](http://www.le64.fr/actualites/nouvelle-organisation-des-solidarites-humaines-les-sdsei.html) que sont les services départementaux des solidarités et de l'insertion.

**Comment by monbocal** [comment]
En lien avec https://github.com/betagouv/annuaire-api/pull/39

**Comment by guillett** [comment]
Done by @monbocal :clap:
