### ISSUE TITLE
Ajouter les points d'accueil physiques de Saône et Loire

### ISSUE THREAD

**Issue by guillett** [betagouv/annuaire-api#67]
Cf email du 05/02/2019 à 11:35,.

**Comment by alexsegura** [comment]
https://www.data.gouv.fr/fr/datasets/implantations-territoriales-de-laction-sociale/

**Comment by alexsegura** [comment]
J'ai un problème avec ce fichier 😞

Déjà, il est encodé en `UTF16LE` (?). 
Et j'ai des erreurs `Unexpected whitespace` quand je le parse.
