### ISSUE TITLE
Ajout des points d'accueil Métropole de Lyon

### ISSUE THREAD

**Issue by charlottelecuit** [betagouv/annuaire-api#75]
Ils n'arrivent pas à mettre à jour le jeu de données sur data.gouv.fr, ils me proposent donc deux liens : 
1. un sur geo.data.gouv : https://geo.data.gouv.fr/fr/datasets/8d1b71d44ef541cf7840829cdbac5e3bd26ef737
2. un sur leur site d'open data grand lyon : https://data.grandlyon.com/services/maisons-de-la-mftropole-de-lyon/

**tag** : MDS

**Comment by alexsegura** [comment]
@charlottelecuit les "Maisons de la Métropole" c'est quel type d'établissement du coup ? MDS ?

**Comment by charlottelecuit** [comment]
Oui c'est la même catégorie @alexsegura
