### ISSUE TITLE
Mettre à jour Node sur le serveur

### ISSUE THREAD

**Issue by alexsegura** [betagouv/annuaire-api#81]
- [ ] Installer Node.js `10.x` avec nvm
- [ ] Installer PM2 & Yarn globalement avec la nouvelle version de Node.js (pas sûr)
- [ ] Modifier le script `deploy.sh`
- [ ] Déployer

**Comment by jdesboeufs** [comment]
Obsolète non ?
Node.js 12 semble utilisé partout.

**Comment by guillett** [comment]
Oui je pense que tu as raison. Je ferme. Merci !
